#!/bin/bash
#_______________________________________________________________________________
#

#Job name
#PBS -N Elastic-06_02
#number of nodes and limit of the execution time (hours:minutes:seconds)
#PBS -l nodes=1:ppn=32
#PBS -l walltime=720:00:00
#type of the queue (smallRam or bigRam)
#PBS -q smallRam

cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=1

mpirun -n 16 /scratch/pavone/vdW/exciting/bin/excitingmpi

#_______________________________________________________________________________
