Mulliken and Loewdin gross orbital population 

  atom#    atom   basisfunction     Mulliken GP      Loewdin GP
      1       U             6s            1.94            1.93
                            7s            0.26            0.43
                          6p_y            1.98            1.96
                          6p_z            1.98            1.96
                          6p_x            1.98            1.96
                         6d_xy            0.32            0.37
                         6d_yz            0.32            0.37
                        6d_z^2            0.40            0.56
                         6d_xz            0.32            0.37
                    6d_x^2-y^2            0.40            0.56
                5f_y(3x^2-y^2)            0.40            0.41
                        5f_xyz            0.00            0.00
                       5f_yz^2            0.34            0.35
                        5f_z^3            0.48            0.50
                       5f_xz^2            0.34            0.35
                 5f_z(x^2-y^2)            0.26            0.26
                5f_x(x^2-3y^2)            0.40            0.41
                         total           12.13           12.74

      2       O             2s            1.83            1.69
                          2p_y            1.47            1.46
                          2p_z            1.66            1.64
                          2p_x            1.66            1.64
                         total            6.62            6.42

      3       O             2s            1.83            1.69
                          2p_y            1.66            1.64
                          2p_z            1.66            1.64
                          2p_x            1.47            1.46
                         total            6.62            6.42

      4       O             2s            1.83            1.69
                          2p_y            1.66            1.64
                          2p_z            1.47            1.46
                          2p_x            1.66            1.64
                         total            6.62            6.42

