Electrostatic site potentials (in V) using Ewald splitting parameter 3.14
This first parameter is a default value that was determined by LOBSTER

  atom#    atom      Potential       Potential
                    (Mulliken)       (Loewdin)
      1       U         -17.87          -12.02 
      2       O           8.08            5.43 
      3       O           8.07            5.43 
      4       O           8.07            5.43 

Madelung Energy (eV)    -24.28          -10.99 
