Mulliken and Loewdin gross orbital population 

  atom#    atom   basisfunction     Mulliken GP      Loewdin GP
      1      Si             3s            1.33            1.15
                          3p_y            0.89            0.95
                          3p_z            0.89            0.95
                          3p_x            0.89            0.95
                         total            4.00            4.00

      2      Si             3s            1.33            1.15
                          3p_y            0.89            0.95
                          3p_z            0.89            0.95
                          3p_x            0.89            0.95
                         total            4.00            4.00

