Mulliken and Loewdin gross orbital population 

  atom#    atom   basisfunction     Mulliken GP      Loewdin GP
      1      Fe             4s            1.15            1.11
                         3d_xy            1.42            1.43
                         3d_yz            1.42            1.43
                        3d_z^2            1.29            1.30
                         3d_xz            1.42            1.43
                    3d_x^2-y^2            1.29            1.30
                         total            8.00            8.00

      2      Fe             4s            1.15            1.11
                         3d_xy            1.42            1.43
                         3d_yz            1.42            1.43
                        3d_z^2            1.29            1.30
                         3d_xz            1.42            1.43
                    3d_x^2-y^2            1.29            1.30
                         total            8.00            8.00

