MULLIKEN and LOEWDIN POPULATION ANALYSIS 

  atom#    atom      Mulliken charge       Loewdin charge
      1      Ba                 2.15                 1.72
      2      Ti                 0.78                 1.11
      3       O                -0.94                -0.91
      4       O                -0.94                -0.91
      5       O                -1.03                -1.01

          total                -0.00                -0.00
