Mulliken and Loewdin gross orbital population 

  atom#    atom   basisfunction     Mulliken GP      Loewdin GP
      1      Ba             5s            1.77            1.83
                            6s            0.13            0.53
                          5p_y            1.98            1.97
                          5p_z            1.99            1.99
                          5p_x            1.98            1.97
                         total            7.85            8.28

      2      Ti             3s            1.92            1.91
                            4s            1.19            0.74
                          3p_y            2.00            2.00
                          3p_z            2.00            2.00
                          3p_x            2.00            2.00
                         3d_xy            0.32            0.33
                         3d_yz            0.40            0.42
                        3d_z^2            0.50            0.54
                         3d_xz            0.40            0.42
                    3d_x^2-y^2            0.49            0.53
                         total           11.22           10.89

      3       O             2s            1.86            1.79
                          2p_y            1.77            1.77
                          2p_z            1.75            1.76
                          2p_x            1.56            1.59
                         total            6.94            6.91

      4       O             2s            1.86            1.79
                          2p_y            1.56            1.59
                          2p_z            1.75            1.76
                          2p_x            1.77            1.77
                         total            6.94            6.91

      5       O             2s            1.88            1.80
                          2p_y            1.73            1.74
                          2p_z            1.69            1.72
                          2p_x            1.73            1.74
                         total            7.03            7.01

