Electrostatic site potentials (in V) using Ewald splitting parameter 3.14
This first parameter is a default value that was determined by LOBSTER

  atom#    atom      Potential       Potential
                    (Mulliken)       (Loewdin)
      1      Ba         -16.96          -14.11 
      2      Ti         -14.02          -15.90 
      3       O           7.87            8.62 
      4       O           7.87            8.62 
      5       O          11.26           11.18 

Madelung Energy (eV)    -36.87          -34.44 
